### ISSUE TITLE
Poetry could not find a pyproject.toml file in

### ISSUE THREAD

**Issue by nicopassaglia** [moneymeets/action-beanstalk-deploy#21]
While running the eb deployment action I ran into this issue. Any ideas?

```
Run poetry lock --check
  poetry lock --check
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.6/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.6/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.6/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.6/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.6/x64/lib

Poetry could not find a pyproject.toml file in /home/runner/work/deal-wins/deal-wins or its parents
```

**Comment by nicopassaglia** [comment]
```
name: Deploy to ECR

on:
  push:
    branches: [deploy_test_branch]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push frontend to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend-repository
          IMAGE_TAG: latest
          REACT_APP_GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
        run: |
          docker build -f Dockerfile.front --build-arg REACT_APP_GOOGLE_CLIENT_ID -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push backend to Amazon ECR
        env:
          ECR_REGISTRY_BACK: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_BACK: backend-repository
          IMAGE_TAG_BACK: latest
        run: |
          docker build -f Dockerfile.back -t $ECR_REGISTRY_BACK/$ECR_REPOSITORY_BACK:$IMAGE_TAG_BACK .
          docker push $ECR_REGISTRY_BACK/$ECR_REPOSITORY_BACK:$IMAGE_TAG_BACK

      - name: Deploy EB
        uses: moneymeets/action-beanstalk-deploy@master
        with:
          application_name: KAWIN-PROD
          docker_compose_path: "${{github.workspace}}/aws/docker-compose.yml"
          environment_name: Kawinprod-env-1
          version_label: ${{github.sha}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
```

This is my actions file and here is my docker compose

```
version: "3.3"
services:
  frontend:
    container_name: frontend
    image: 918429180043.dkr.ecr.us-east-1.amazonaws.com/frontend-repository:latest
    env_file:
      - /opt/elasticbeanstalk/deployment/env.list
    ports:
      - "80:80"
  backend:
    image: 918429180043.dkr.ecr.us-east-1.amazonaws.com/backend-repository:latest
    env_file:
      - /opt/elasticbeanstalk/deployment/env.list
    container_name: backend
    ports:
      - "5000:5000"
```
